#!/bin/bash
# =============================================================================
# KDE and Chrome Configuration Script — SECURITY HARDENED
# Locks down KDE shortcuts, configures Chrome, and injects toolbar
# =============================================================================

# =============================================================================
# KDE Shortcut Hardening
# Disable dangerous shortcuts that could give users shell/system access
# =============================================================================
echo "**** Applying KDE security hardening ****"

mkdir -p /config/.config

# --- Disable KRunner (Alt+Space / Alt+F2) ---
# KRunner can execute arbitrary commands — critical security risk
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "org.kde.krunner.desktop" --key "_launch" "none,none,KRunner"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "krunner.desktop" --key "_launch" "none,none,KRunner"
# Also disable the Alt+F2 "Run Command" shortcut
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "kwin" --key "Run Command" "none,none,Run Command"

# --- Disable Alt+F4 (Close Window) ---
# Prevent users from closing Chrome and being stuck on bare desktop
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "kwin" --key "Window Close" "none,none,Close Window"

# --- Disable Session Logout/Restart/Shutdown shortcuts ---
# Prevent Ctrl+Alt+Del and other session-ending shortcuts
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "ksmserver" --key "Log Out" "none,none,Log Out"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "ksmserver" --key "Log Out Without Confirmation" "none,none,Log Out Without Confirmation"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "ksmserver" --key "Shut Down Without Confirmation" "none,none,Shut Down Without Confirmation"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "ksmserver" --key "Reboot Without Confirmation" "none,none,Reboot Without Confirmation"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "ksmserver" --key "Halt Without Confirmation" "none,none,Halt Without Confirmation"

# --- Disable terminal-related shortcuts ---
# Terminals are already uninstalled, but disable shortcuts to avoid errors
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "org.kde.konsole.desktop" --key "_launch" "none,none,Konsole"

# --- Disable Activities / Desktop switching (prevents escape from session) ---
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "kwin" --key "Show Desktop" "none,none,Show Desktop"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "kwin" --key "Switch to Desktop 1" "none,none,Switch to Desktop 1"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "kwin" --key "Switch to Desktop 2" "none,none,Switch to Desktop 2"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "kwin" --key "Switch to Desktop 3" "none,none,Switch to Desktop 3"
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "kwin" --key "Switch to Desktop 4" "none,none,Switch to Desktop 4"

# --- Disable screen locking ---
kwriteconfig5 --file /config/.config/kglobalshortcutsrc \
    --group "ksmserver" --key "Lock Session" "none,none,Lock Session"

chown abc:abc /config/.config/kglobalshortcutsrc 2>/dev/null || true

echo "**** KDE shortcuts hardened ****"

# =============================================================================
# Chrome Configuration
# =============================================================================

# Pre-configure Chrome preferences
CHROME_CONFIG_DIR="/config/.config/google-chrome"
mkdir -p "$CHROME_CONFIG_DIR/Default"

# Create Local State
if [ ! -f "$CHROME_CONFIG_DIR/Local State" ]; then
    cat > "$CHROME_CONFIG_DIR/Local State" << 'EOF'
{
  "browser": {
    "enabled_labs_experiments": []
  },
  "user_experience_metrics": {
    "reporting_enabled": false
  }
}
EOF
fi

# Create Default preferences
if [ ! -f "$CHROME_CONFIG_DIR/Default/Preferences" ]; then
    cat > "$CHROME_CONFIG_DIR/Default/Preferences" << 'EOF'
{
  "session": {
    "restore_on_startup": 4
  },
  "browser": {
    "show_home_button": false,
    "check_default_browser": false,
    "custom_chrome_frame": false
  },
  "omnibox": {
    "prevent_url_elisions": true
  },
  "extensions": {
    "theme": {
      "use_system": false
    }
  },
  "profile": {
    "default_content_setting_values": {}
  },
  "autogenerated": {
    "theme": {
      "color": -7864065
    }
  },
  "webkit": {
    "webprefs": {
      "darkModeEnabled": true
    }
  }
}
EOF
fi

chown -R abc:abc "$CHROME_CONFIG_DIR"

# GTK dark theme
mkdir -p /config/.config/gtk-3.0
cat > /config/.config/gtk-3.0/settings.ini << EOF
[Settings]
gtk-theme-name=Adwaita-dark
gtk-application-prefer-dark-theme=true
EOF

chown -R abc:abc /config/.config/gtk-3.0

# =============================================================================
# Runtime Security Lockdown
# =============================================================================
chmod 700 /root /boot 2>/dev/null || true
chmod 700 /custom-cont-init.d 2>/dev/null || true
chmod 711 /bin /sbin /usr/bin /usr/sbin /usr/local/bin 2>/dev/null || true
chmod 755 /config 2>/dev/null || true
chmod 1777 /tmp 2>/dev/null || true
mkdir -p /config/Downloads 2>/dev/null || true
chown -R abc:abc /config 2>/dev/null || true

# =============================================================================
# KDE Desktop Configuration
# =============================================================================

# KDE Compositing: Enable with balanced latency policy
# LatencyPolicy: 0=ExtremelyLow, 1=Low, 2=Medium(balanced), 3=High, 4=ExtremelyHigh
kwriteconfig5 --file /config/.config/kwinrc --group Compositing --key Enabled true
kwriteconfig5 --file /config/.config/kwinrc --group Compositing --key LatencyPolicy 2
chown abc:abc /config/.config/kwinrc 2>/dev/null || true
# Reload KWin compositor if already running
su -c "DISPLAY=:1 dbus-send --session --dest=org.kde.KWin --type=method_call /Compositor org.kde.kwin.Compositing.resume" abc 2>/dev/null || true

# Set default cursor theme to Adwaita
kwriteconfig5 --file /config/.config/kcminputrc --group Mouse --key cursorTheme Adwaita
chown abc:abc /config/.config/kcminputrc 2>/dev/null || true

# =============================================================================
# Selkies Patches
# =============================================================================

# Fix scroll magnitude: cap to 1 event per wheel notch (server-side)
SELKIES_INPUT="/lsiopy/lib/python3.12/site-packages/selkies/input_handler.py"
if [ -f "$SELKIES_INPUT" ]; then
  sed -i 's/for _ in range(max(1, scroll_magnitude))/for _ in range(1)/' "$SELKIES_INPUT"
  echo "**** Scroll magnitude patched ****"
fi

# Inject Cloud Browser toolbar into Selkies web UI
# (Selkies populates /usr/share/selkies/web/ at startup, so we inject at runtime)
(
  SELKIES_WEB="/usr/share/selkies/web"
  for i in $(seq 1 30); do
    if [ -f "$SELKIES_WEB/index.html" ]; then
      cp /opt/toolbar/toolbar.css "$SELKIES_WEB/toolbar.css"
      cp /opt/toolbar/toolbar.js  "$SELKIES_WEB/toolbar.js"
      if ! grep -q 'toolbar.css' "$SELKIES_WEB/index.html"; then
        sed -i 's|</head>|<link rel="stylesheet" href="toolbar.css"></head>|' "$SELKIES_WEB/index.html"
      fi
      if ! grep -q 'toolbar.js' "$SELKIES_WEB/index.html"; then
        sed -i 's|</body>|<script src="toolbar.js"></script></body>|' "$SELKIES_WEB/index.html"
      fi
      echo "**** Toolbar injected into Selkies ****"
      break
    fi
    sleep 1
  done
) &

echo "**** KDE and Chrome configured ****"
